# The URL the site will be built for
base_url = "https://windwanderer.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Wind Wanderer"
description = "Gone sailing"

theme = "zola-clean-blog"

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
theme = "github-dark"

[extra]
author = "Elvira & Christoph"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "https://www.marinetraffic.com/en/ais/details/ships/shipid:8822088/mmsi:218039140/imo:0/vessel:WANDERER", name="Position"},
    {url = "$BASE_URL/boats", name = "Boot"},
    {url = "$BASE_URL/routes", name = "Routen"},
    {url = "https://www.instagram.com/sy.wanderer", name = "Instagram"},
    {url = "$BASE_URL/contact", name = "Kontakt"}
]
clean_blog_social = []
